name: NODE CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v1
    - name: Dmitry841
      run: make install
    - name: Run linter
      run: make lint
